### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by yoavst** [OgarProject/Ogar2-Server#1]
Hi, I'm an Android Developer, so I'm only familiar with Gradle config.
I want to compile Ogar2-Server package, but I can't without Ogar2-API package. However, the Ogar2-API package is not available on maven, so build fails. Can you upload it to snapshot repo or make the github a repo?

**Comment by ryush00** [comment]
I also wondered. It's too difficult to compile. And I found out this

https://github.com/OgarProject/Ogar2-API

**Comment by ghost** [comment]
you need to first compile the API from the https://github.com/OgarProject/Ogar2-API repository, then put the API jar to the folder of ogar2-server repository and do "mvn clean install"

**Comment by Agarian** [comment]
but how do i compile??

**Comment by Agarian** [comment]
This is pointless. The topic is "How to compile" but no one said how to compile!

**Comment by yoavst** [comment]
Actually they have answered this...
