### ISSUE TITLE
taken care of

### ISSUE THREAD

**Issue by ghost** [OgarProject/Ogar2-Server#11]

**Comment by z3ntu** [comment]
This should work on all Linux systems. (Maven & Git has to be installed, use your favorite package manager)

```
git clone https://github.com/OgarProject/Ogar2-API.git
git clone https://github.com/OgarProject/Ogar2-Server.git
cd Ogar2-API
mvn
cp target/ogar-api-2.0-SNAPSHOT.jar ../Ogar2-Server/
cd ../Ogar2-Server
mvn clean install
```

Final `.jar` file is in `target/ogar-server-2.0-SNAPSHOT.jar` of the Ogar2-Server folder

**Comment by ghost** [comment]
i do not have linux. I seriously do not know what any of that is or means. I AM NEW HERE!

**Comment by z3ntu** [comment]
Please close this and look at the other issue.

**Comment by ghost** [comment]
screw this

**Comment by elitajmx** [comment]
ikr, noone tells how to do shit at least add me on fucking skype and tell me
cunts.

**Comment by z3ntu** [comment]
You are really polite, just sayin'... And Ogar2 seems dead to me btw

**Comment by ghost** [comment]
is it any different than regular ogar besides the build? like better playerbots, split physics, color etc.

**Comment by z3ntu** [comment]
I have no idea and I suppose Ogar (1) has more features than Ogar 2 atm

**Comment by ghost** [comment]
then i wasted my time with this build.

**Comment by jacobduba** [comment]
z3ntu's build should work on windows too.

**Comment by elitajmx** [comment]
can someone tlel me how do i make the better split physics and color thats all 
and MooShoe how u mean z3ntu's build i searched on google and it doesnt show him

**Comment by RobinTheGod** [comment]
Agar 2 has infinite Power because it runs in Java!

What do you mean, "different than regular ogar besides the build?" xD

You want to make a really awesome Server? 
-> Use a Awesome Programming Language with cool free Libraries and crazy nice open source Frameworks! ;P 

different than regular ogar besides the build.. xD

**Comment by ghost** [comment]
where do i even get maven?

**Comment by ThunderGemios10** [comment]
@Agarian Here you go: https://maven.apache.org/download.cgi

**Comment by ghost** [comment]
But thats source code

**Comment by ThunderGemios10** [comment]
@Agarian Yes. But that's maven. You'll need Git too to compile Ogar2

**Comment by ThunderGemios10** [comment]
@Agarian Good news! I just compiled Ogar2-Server for you!
Download it at my forked version at "releases".
Or i'll link it for you.
https://github.com/ThunderGemios10/Ogar2-Server/releases

**Comment by ghost** [comment]
THANK YOU

**Comment by ghost** [comment]
lol ogar unlimited is better

**Comment by ThunderGemios10** [comment]
@Agarian .-. Do you want to use Ogar2 or Ogar Unlimited.?

**Comment by ghost** [comment]
after seeing that all entities are green, that there are no commands, that there is no leaderboard, that the config.json for some reason didn't work, the i choose ogar unlimited. you should try it it has premium skins and other assets of vanilla agar.io! https://github.com/AJS-development/Ogar-unlimited

**Comment by ThunderGemios10** [comment]
@Agarian Did you even read the Ogar2-Server's README? It is under heavy development and does not feature anything yet!

**Comment by ghost** [comment]
Lol i dont see how 17 commits is heavy development. Heavy development can be found in https://github.com/AJS-development/Ogar-unlimited with a whopping 1240+ commits! 
And no i didn't really read it, just skimmed. Don't judge!

**Comment by ThunderGemios10** [comment]
@Agarian Yes, I admit that Ogar-Unlimited is in development in a fast pace.
But the developers on Ogar2 are pushing commits on a rather... slow pace.
