### ISSUE TITLE
Experimental mode not working

### ISSUE THREAD

**Issue by jrgryph** [OgarProject/Ogar2-Server#19]
Here's my console output:

C:\Users\John\Desktop\Games\agar.io\Ogar\src>node index.js
[Game] Ogar - An open source Agar.io server implementation
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Experimental
[Game] Loaded 25 player bots

> TypeError: Cannot read property 'config' of undefined
>     at Cell.Food (C:\Users\John\Desktop\Games\agar.io\Ogar\src\entity\Food.js:11:24)
>     at Cell.MotherCell.spawnFood (C:\Users\John\Desktop\Games\agar.io\Ogar\src\gamemodes\Experimental.js:234:13)
>     at Cell.MotherCell.update (C:\Users\John\Desktop\Games\agar.io\Ogar\src\gamemodes\Experimental.js:164:18)
>     at Mode.Experimental.updateMotherCells (C:\Users\John\Desktop\Games\agar.io\Ogar\src\gamemodes\Experimental.js:36:16)
>     at Mode.Experimental.onTick (C:\Users\John\Desktop\Games\agar.io\Ogar\src\gamemodes\Experimental.js:113:11)
>     at GameServer.gamemodeTick (C:\Users\John\Desktop\Games\agar.io\Ogar\src\GameServer.js:367:19)
>     at GameServer.mainLoop (C:\Users\John\Desktop\Games\agar.io\Ogar\src\GameServer.js:387:29)
>     at wrapper [as _onTimeout](timers.js:270:19)
>     at Timer.listOnTimeout (timers.js:89:15)

**Comment by elitajmx** [comment]
jrgryph whats your skype?
