### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MrDini123** [OgarProject/Ogar2-Server#20]
Hi!

When I try to compile the source using mvn command, or mvn package it shows the following error:

<hashtag> mvn
[INFO] Scanning for projects...
[INFO]                                                                                          [INFO] ------------------------------------------------------------------------                 [INFO] Building Ogar Server 2.0-SNAPSHOT                                                        [INFO] ------------------------------------------------------------------------                 [WARNING] The POM for com.ogarproject:ogar-api:jar:2.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.638 s
[INFO] Finished at: 2016-01-21T21:11:13+00:00
[INFO] Final Memory: 4M/10M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ogar-server: Could not resolve dependencies for project com.ogarproject:ogar-server:jar:2.0-SNAPSHOT: Could not find artifact com.ogarproject:ogar-api:jar:2.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I tried to compile to a nas with armv5 processor.

What's wrong?

Thanks for UR answer! :D

**Comment by nevivurn** [comment]
It needs to have https://github.com/OgarProject/Ogar2-API, so build that as well. However, I'm not even sure if ogar2 is even working yet.

**Comment by MrDini123** [comment]
Hello!

Many thanks for the answer! :)

But when I try to compile the API it shows an other error: :/

[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Ogar API 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ogar-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.       [INFO] skip non existing resourceDirectory /build/Ogar2-API/src/main/resources                                  [INFO]                                                          [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ogar-api ---                                                   [INFO] Changes detected - recompiling the module!
[INFO] Compiling 22 source files to /build/Ogar2-API/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :                                     [INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.101 s
[INFO] Finished at: 2016-01-22T16:21:35+00:00
[INFO] Final Memory: 6M/14M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project ogar-api: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I've ejdk 1.8.0.x installed (8.x Java), and I set the JAVA_HOME variable to path of jre...

Thanks!

**Comment by nevivurn** [comment]
It works for me. Try setting your JAVA_HOME to your jdk, not jre. For me, the jre stuff is in
`/opt/java/jdk1.8.0_65/jre/bin`, but jdk stuff is in `/opt/java/jdk1.8.0_65/bin`.

**Comment by ThunderGemios10** [comment]
You don't need to compile anymore.
You can use my compiled build!
Here's the link:
http://ci.thundergemios10.com/job/Ogar2-Server/

**Comment by ThunderGemios10** [comment]
@forairan Close?

**Comment by MrDini123** [comment]
Thanks!
