### ISSUE TITLE
Performance Test with 999 Bots - Ogar V2 much slower than Ogar V1 - But isn't Multithreading faster?

### ISSUE THREAD

**Issue by RobinTheGod** [OgarProject/Ogar2-Server#21]
hey ;P

Performance Test with 999 Bots shows -> Ogar V2 seems slower than Ogar V1.
(OgarV2 laggs like hell - and OgarV1 doesn't)

As Ogar V2 allows Multithreading, OgarV2 should be faster than OgarV1 right?

Or have Bots become more complex?
Whats the cause?
I'm looking to create a OgarV2 Server and would like to know how easy it is to scale it. ;P

,Greeting emtonsti

**Comment by baconga** [comment]
I feel it a lot more performance!

**Comment by avafloww** [comment]
Keep in mind 999 users is a lot for _any_ server. The official servers are actually split into many separate servers per region - there isn't actually 78,000 players on North America at once, for example. With a reasonable number of users, Ogar 2 should be faster under default settings, as network IO isn't performed on the same thread that performs world/entity ticking.

Also, Ogar 2 is still under heavy development, and isn't ready for production use. However, if you'd like to try multithreaded ticking, there's a _very_ experimental flag you can use when launching the server to change the number of tick threads:

```
java -DtickThreads=8 -jar whatever-your-ogar-server-jar-is-named.jar
```

Replace 8 with however many tick threads you want to attempt using; I would recommend not having this value any higher than the number of threads your CPU has, as it'd be counterproductive at that point. As I said, this flag is _extremely_ experimental, and might cause very strange oddities or crashes - use at your own risk.
